apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: {{ .Values.greeting.replicaCount }}
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: {{ .Values.greeting.image }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: "http"
        - containerPort: {{ .Values.service.internalDebugPort }}
          name: "debug"
