apiVersion: apps/v1
kind: Deployment
metadata:
    name: springbootapp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: springbootapp
    template:
        metadata:
            labels:
                app: springbootapp
        spec:
            containers:
            - name: springbootapp
              image: tarun00000/springbootapp:1
              imagePullPolicy: Always
              ports:
              - containerPort: 8008
                name: "http"
              - containerPort: 5005
                name: "debug"

---

apiVersion: v1
kind: Service
metadata:
    name: springbootapp
spec:
    selector:
        app: springbootapp
    ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    type: LoadBalancer