greeting:
  image: tarun00000/springbootapp
  replicaCount: 1

image:
  tag: 1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  externalPort: 8080
  internalPort: 8080
  externalDebugPort: 5005
  internalDebugPort: 5005